config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'root#index', as: :root
  resources :students
  resources :subjects
  resources :grade_classes

end

app/models/grade_class.rb
class GradeClass < ActiveRecord::Base
  has_many :students
  has_many :grade_class_subjects
  has_many :subjects, through: :grade_class_subjects

  def subject_names
    subjects.collect {|sub| sub.name }
  end
end

app/models/grade_class_subject.rb
class GradeClassSubject < ActiveRecord::Base
  belongs_to :grade_class
  belongs_to :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :grade_class

  validates :name, :role_no, presence: true
  validates :role_no, uniqueness: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :grade_class_subjects
  has_many :grade_classes, through: :grade_class_subjects

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grade_classes_controller.rb
class GradeClassesController < ApplicationController
  before_action :set_grade_class, only: [:show, :edit, :update, :destroy]

  before_action :load_subject, only: [:new, :edit]
  # GET /grade_classes
  # GET /grade_classes.json
  def index
    @grade_classes = GradeClass.all
  end

  # GET /grade_classes/1
  # GET /grade_classes/1.json
  def show
  end

  # GET /grade_classes/new
  def new
    @grade_class = GradeClass.new
  end

  # GET /grade_classes/1/edit
  def edit
  end

  # POST /grade_classes
  # POST /grade_classes.json
  def create
    @grade_class = GradeClass.new(grade_class_params)

    respond_to do |format|
      if @grade_class.save
        format.html { redirect_to @grade_class, notice: 'Grade class was successfully created.' }
        format.json { render :show, status: :created, location: @grade_class }
      else
        format.html { render :new }
        format.json { render json: @grade_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grade_classes/1
  # PATCH/PUT /grade_classes/1.json
  def update
    respond_to do |format|
      if @grade_class.update(grade_class_params)
        format.html { redirect_to @grade_class, notice: 'Grade class was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade_class }
      else
        format.html { render :edit }
        format.json { render json: @grade_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grade_classes/1
  # DELETE /grade_classes/1.json
  def destroy
    @grade_class.destroy
    respond_to do |format|
      format.html { redirect_to grade_classes_url, notice: 'Grade class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade_class
      @grade_class = GradeClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_class_params
      params.require(:grade_class).permit(:name, subject_ids: [])
    end

    def load_subject
      @subjects = Subject.all
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :load_grade_classes, only: [:new, :edit]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :role_no, :grade_class_id)
    end

    def load_grade_classes
      @grade_classes = GradeClass.all
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grade_classes_helper.rb
module GradeClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/grade_classes/_form.html.erb
<%= form_for(@grade_class) do |f| %>
  <% if @grade_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade_class.errors.count, "error") %> prohibited this grade_class from being saved:</h2>

      <ul>
      <% @grade_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <fieldset>
      <legend>Subjects</legend>
      <% subject_ids = @grade_class.subject_ids %>
      <% @subjects.each do |subject| %>
        <p>
          <%= check_box_tag 'grade_class[subject_ids][]', subject.id, subject_ids.include?(subject.id) %>&nbsp;
          <%= subject.name %>
        </p>
      <% end %>
    </fieldset>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grade_classes/edit.html.erb
<h1>Editing Grade Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade_class %> |
<%= link_to 'Back', grade_classes_path %>

app/views/grade_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grade Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subjects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grade_classes.each do |grade_class| %>
      <tr>
        <td><%= grade_class.name %></td>
        <td><%= grade_class.subject_names.join(', ') %></td>
        <td><%= link_to 'Show', grade_class %></td>
        <td><%= link_to 'Edit', edit_grade_class_path(grade_class) %></td>
        <td><%= link_to 'Destroy', grade_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade class', new_grade_class_path %> |
<%= link_to 'Back', root_path %>

app/views/grade_classes/new.html.erb
<h1>New Grade Class</h1>

<%= render 'form' %>

<%= link_to 'Back', grade_classes_path %>

app/views/grade_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @grade_class.name %>
</p>
<p>
  <strong>Subject:</strong>
  <%= @grade_class.subject_names.join(', ') %>
</p>

<%= link_to 'Edit', edit_grade_class_path(@grade_class) %> |
<%= link_to 'Back', grade_classes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollegePortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/root/index.html.erb
<h1>College Portal</h1>

<p><%= link_to 'Students', students_path %></p>
<p><%= link_to 'Subjects', subjects_path %></p>
<p><%= link_to 'Grade Classes', grade_classes_path %></p>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :role_no %><br>
    <%= f.text_field :role_no %>
  </div>
  <div class="field">
    <%= f.label :grade_class %><br>
    <%= f.select :grade_class_id, @grade_classes.collect { |gc| [gc.name, gc.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role no</th>
      <th>Grade Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.role_no %></td>
        <td><%= student.grade_class.try(:name) || '-' %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %> |
<%= link_to 'Back', root_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Role no:</strong>
  <%= @student.role_no %>
</p>

<p>
  <strong>Grade Class:</strong>
  <%= @student.grade_class.try(:name) || '-' %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %> |
<%= link_to 'Back', root_path %> 

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>